
###################### Sample info ######################


SAMPLE:
  Treated_rep1: SRR6461133
  Treated_rep2: SRR6461134
  Treated_rep3: SRR6461135
  Control_rep1: SRR6461139 
  Control_rep2: SRR6461140
  Control_rep3: SRR6461141



END: 
  - 1
  - 2




###################### Reference info ######################

REFERENCE:
  LINK: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/'
  FILE: 
    GENOME: 'GRCh38.primary_assembly.genome.fa'
    ANNOTATION: 'gencode.v37.primary_assembly.annotation.gtf'
  
# e.g. 
# Reference genome link: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh38.primary_assembly.genome.fa.gz
# Reference annotation (GTF) link: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.primary_assembly.annotation.gtf.gz 

###################### Extra-setting info ######################

INDEX_HISAT: "reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)

FASTQ_EXT: '.fastq.gz'

  
