---
###################### Sample info ######################

END: 
  - 1



FASTQ_PREFIX:
  - DMSO_rep1
  - DMSO_rep2
  - DMSO_rep3
  - SR0813_rep1
  - SR0813_rep2
  - SR0813_rep3


###################### Reference info ######################


REFERENCE_LINK:
  GENOME: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa.gz'
    - 'GRCh38.primary_assembly.genome.fa'
  ANNOTATION: 
    - 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf.gz'
    - 'gencode.v37.primary_assembly.annotation.gtf'


###################### Extra-setting info ######################

INDEX_HISAT: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)

FASTQ_EXT: '.fastq.gz'


