
GTF: "reference/gencode.v36.primary_assembly.annotation.gtf" # Assigns path to .gtf file


INDEX_HISAT: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)


THREADS: 8     # Assigns the number of threads

STAR_OUT: "star_output"  # Assigns STAR output directory

HISAT_OUT: "hisat2_output"  # Assigns HISAT2 output directory

FASTQ_DIR: 'fastq_se/'

FASTQ_PREFIX:
  - 'Ctrl'
  - 'Treatment'



FASTQ_EXT: '.fastq.gz'
  

END: 
  - 1


