
SAMPLE:
  SRR8245179: Treated
  SRR8245176: Untreated




FASTQ_LIST:
  - Treated_1
  - Treated_2
  - Untreated_1
  - Untreated_2

END: 
  - 1
  - 2


SRA:
  - SRR8245179
  - SRR8245176



GTF: "reference/gencode.v36.primary_assembly.annotation.gtf" # Assigns path to .gtf file

INDEX_HISAT: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/hisat2_index/hisat2_index" # Assigns hisat2 index files (e.g.reference/hisat2_index/hisat2_index.1.ht2, reference/hisat2_index/hisat2_index.2.ht2, ...)



THREADS: 8     # Assigns the number of threads

STAR_OUT: "star_output"  # Assigns STAR output directory

HISAT2_OUT: "hisat2_output"  # Assigns HISAT2 output directory

FASTQ_DIR: 'fastq_pe/'

FASTQ_EXT: '.fastq.gz'

FASTQ_PREFIX:
  - Treated
  - Untreated



  
